/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package plaatidearvutamine;

import java.awt.Color;

/**
 *
 * @author paul.maimik
 */
public class PlaatideArvutamineUI extends javax.swing.JFrame {

    double poX; // Põranda pikkus
    double poY; // Põranda laius
    double plX; // Plaadi pikkus
    double plY; // Plaadi laius
    double vu;  // Vuugivage pikkus

    /**
     * Creates new form PlaatideArvutamineUI
     */
    public PlaatideArvutamineUI() {
        initComponents();
        getContentPane().setBackground(new Color(200, 200, 200));
        jLabel5.setVisible(false);
        spnVuugivahePikkus.setVisible(false);
        cmbVuugivahePikkus.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cmbPorandPikkus = new javax.swing.JComboBox<>();
        cmbPorandLaius = new javax.swing.JComboBox<>();
        cmbPlaatPikkus = new javax.swing.JComboBox<>();
        cmbPlaatLaius = new javax.swing.JComboBox<>();
        cmbVuugivahePikkus = new javax.swing.JComboBox<>();
        chkVuugivahe = new javax.swing.JCheckBox();
        spnPorandPikkus = new javax.swing.JSpinner();
        spnPorandLaius = new javax.swing.JSpinner();
        spnPlaatPikkus = new javax.swing.JSpinner();
        spnPlaatLaius = new javax.swing.JSpinner();
        spnVuugivahePikkus = new javax.swing.JSpinner();
        chkTervedPlaadid = new javax.swing.JCheckBox();
        chkLoigatudPlaadid = new javax.swing.JCheckBox();
        btnArvuta = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtaData = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Plaatide arvutamine");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(200, 200, 200));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Andmed", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        jLabel1.setText("Põranda pikkus:");

        jLabel2.setText("Põranda laius:");

        jLabel3.setText("Plaadi pikkus:");

        jLabel4.setText("Plaadi laius:");

        jLabel5.setText("Vuugivahe:");

        cmbPorandPikkus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Millimeeter", "Sentimeeter", "Meeter" }));
        cmbPorandPikkus.setSelectedIndex(1);

        cmbPorandLaius.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Millimeeter", "Sentimeeter", "Meeter" }));
        cmbPorandLaius.setSelectedIndex(1);

        cmbPlaatPikkus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Millimeeter", "Sentimeeter", "Meeter" }));
        cmbPlaatPikkus.setSelectedIndex(1);

        cmbPlaatLaius.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Millimeeter", "Sentimeeter", "Meeter" }));
        cmbPlaatLaius.setSelectedIndex(1);

        cmbVuugivahePikkus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Millimeeter", "Sentimeeter", "Meeter" }));
        cmbVuugivahePikkus.setSelectedIndex(1);

        chkVuugivahe.setBackground(new java.awt.Color(200, 200, 200));
        chkVuugivahe.setText("Vuugivahega");
        chkVuugivahe.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                chkVuugivahePropertyChange(evt);
            }
        });

        spnPorandPikkus.setModel(new javax.swing.SpinnerNumberModel(1.0d, 1.0d, 99999.0d, 1.0d));

        spnPorandLaius.setModel(new javax.swing.SpinnerNumberModel(1.0d, 1.0d, 99999.0d, 1.0d));

        spnPlaatPikkus.setModel(new javax.swing.SpinnerNumberModel(1.0d, 1.0d, 99999.0d, 1.0d));

        spnPlaatLaius.setModel(new javax.swing.SpinnerNumberModel(1.0d, 1.0d, 99999.0d, 1.0d));

        spnVuugivahePikkus.setModel(new javax.swing.SpinnerNumberModel(1.0d, 1.0d, 99999.0d, 1.0d));

        chkTervedPlaadid.setBackground(new java.awt.Color(200, 200, 200));
        chkTervedPlaadid.setSelected(true);
        chkTervedPlaadid.setText("Tervete plaatidega");

        chkLoigatudPlaadid.setBackground(new java.awt.Color(200, 200, 200));
        chkLoigatudPlaadid.setText("Lõigatud plaatidega");

        btnArvuta.setBackground(new java.awt.Color(200, 200, 200));
        btnArvuta.setText("Arvuta");
        btnArvuta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnArvutaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spnPorandPikkus, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                    .addComponent(spnPorandLaius)
                    .addComponent(spnPlaatPikkus)
                    .addComponent(spnPlaatLaius)
                    .addComponent(spnVuugivahePikkus))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbPorandLaius, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbPorandPikkus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbPlaatPikkus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbPlaatLaius, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbVuugivahePikkus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(chkLoigatudPlaadid)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(chkVuugivahe))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkTervedPlaadid)
                    .addComponent(btnArvuta, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spnPorandPikkus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(cmbPorandPikkus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spnPorandLaius, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(cmbPorandLaius, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spnPlaatPikkus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(cmbPlaatPikkus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spnPlaatLaius, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(cmbPlaatLaius, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spnVuugivahePikkus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(cmbVuugivahePikkus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkTervedPlaadid)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkLoigatudPlaadid)
                    .addComponent(chkVuugivahe))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnArvuta)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(200, 200, 200));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tulemused", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        txtaData.setEditable(false);
        txtaData.setColumns(20);
        txtaData.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        txtaData.setRows(5);
        jScrollPane1.setViewportView(txtaData);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnArvutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnArvutaActionPerformed
        poX = (double) spnPorandPikkus.getValue();
        poY = (double) spnPorandLaius.getValue();
        plX = (double) spnPlaatPikkus.getValue();
        plY = (double) spnPlaatLaius.getValue();
        if (chkVuugivahe.isSelected()) {
            //txtaData.append("Vuugivahe ei tööta");
            vu = (double) spnVuugivahePikkus.getValue();
        }

        double plaateReasDouble;
        double plaateVeerusDouble;
        double plaateTerveKokkuDouble;
        double plaateLoigatudDouble;
        double plaateKokkuDouble;

        plaateReasDouble = poX / plX;
        plaateVeerusDouble = poY / plY;
        plaateTerveKokkuDouble = (poX / plX) * (poY / plY);
        //plaateLoigatudDouble = (poX - plX) + (poY - plY);
        //double jaak = poX - (plX * plaateReasDouble);
        plaateLoigatudDouble = plaateTerveKokkuDouble % (plaateReasDouble / plaateVeerusDouble);
        //plaateLoigatudDouble = jaak / 2;
        plaateKokkuDouble = plaateTerveKokkuDouble + plaateLoigatudDouble;

        //int loigatudPlaadid = (int) (mahubL * mahubP);
        int plaateVeerus = (int) Math.floor(plaateVeerusDouble);
        int plaateLoigatud = (int) Math.round(plaateLoigatudDouble);
        int plaateTerveKokku = (int) Math.round(plaateTerveKokkuDouble);
        int plaateReas = (int) Math.floor(plaateReasDouble);
        int plaateKokku = (int) Math.round(plaateKokkuDouble);

        if (chkLoigatudPlaadid.isSelected()) {
            // Laius
            chkTervedPlaadid.setSelected(false);
            double mahubL = poX / plX;
            double plaatidePikkusL = plX * mahubL;
            double jaakL = poX - plaatidePikkusL;
            double loigatudPlaadidL = jaakL / 2;
            if (jaakL < (plX / 2) && jaakL > 0) {
                mahubL -= 1;
                plaatidePikkusL = plX * mahubL;
                loigatudPlaadidL = (jaakL + plX) / 2;
            } else if (plaatidePikkusL == poX) {
                loigatudPlaadidL = 0;
            }

            // Pikkus
            double mahubP = poY / plY;
            double plaatidePikkusP = plY * mahubP;
            double jaakP = poY - plaatidePikkusP;
            double loigatudPlaadidP = jaakP / 2;
            if (jaakP < (plY / 2) && jaakP > 0) {
                mahubL -= 1;
                plaatidePikkusP = plY * mahubP;
                loigatudPlaadidP = (jaakP + plY) / 2;
            } else if (plaatidePikkusP == poY) {
                loigatudPlaadidP = 0;
            }

            txtaData.setText("");
            txtaData.append("Terveid plaate kokku: " + plaateTerveKokku + "\n"
                    + "Terveid plaate reas: " + plaateReas + "\n"
                    + "Terveid plaate veerus: " + plaateVeerus + "\n"
                    + "Lõigatud plaate kokku: " + plaateLoigatud + "\n"
                    + "Plaate kokku: " + plaateKokku + "\n");
            System.out.println("Mahub ritta: " + mahubL + "\n"
                    + "Plaatide laius: " + plaatidePikkusL + "\n"
                    + "Lõigatud plaatide laius: " + loigatudPlaadidL + "\n"
                    + "Mahub veergu: " + mahubP + "\n"
                    + "Plaatide pikkus: " + plaatidePikkusP + "\n"
                    + "Lõigatud plaatide pikkus: " + loigatudPlaadidP + "\n");
        } else {
            // Laius
            chkLoigatudPlaadid.setSelected(false);
            double mahubL = poX / plX;
            double plaatidePikkusL = (mahubL * plX) + (mahubL * vu);
            double jaakL = poX - plaatidePikkusL;
            if (jaakL < (plX / 2) && jaakL > 0) {
                plaatidePikkusL = (mahubL * plX) + (mahubL * vu);
            }

            // Pikkus
            double mahubP = poY / plY;
            double plaatidePikkusP = (mahubP * plY) + (mahubP * vu);
            double jaakP = poY - plaatidePikkusP;
            if (jaakP < (plY / 2) && jaakP > 0) {
                plaatidePikkusP = (mahubP * plY) + (mahubP * vu);
            }
            txtaData.setText("");
            txtaData.append("Terveid plaate kokku: " + plaateTerveKokku + "\n"
                    + "Terveid plaate reas: " + plaateReas + "\n"
                    + "Terveid plaate veerus: " + plaateVeerus + "\n"
                    + "Lõigatud plaate kokku: " + plaateLoigatud + "\n"
                    + "Plaate kokku: " + plaateKokku + "\n");
            System.out.println("Mahub ritta: " + mahubL + "\n"
                    + "Plaatide laius: " + plaatidePikkusL + "\n"
                    + "Lõigatud plaatide laius: " + jaakL + "\n"
                    + "Mahub veergu: " + mahubP + "\n"
                    + "Plaatide pikkus: " + plaatidePikkusP + "\n"
                    + "Lõigatud plaatide pikkus: " + jaakP + "\n");
        }
    }//GEN-LAST:event_btnArvutaActionPerformed

    private void chkVuugivahePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_chkVuugivahePropertyChange
        if (chkVuugivahe.isSelected()) {
            jLabel5.setVisible(true);
            cmbVuugivahePikkus.setVisible(true);
            spnVuugivahePikkus.setVisible(true);
        } else {
            jLabel5.setVisible(false);
            cmbVuugivahePikkus.setVisible(false);
            spnVuugivahePikkus.setVisible(false);
        }
    }//GEN-LAST:event_chkVuugivahePropertyChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Windows look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Windows (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PlaatideArvutamineUI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PlaatideArvutamineUI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PlaatideArvutamineUI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PlaatideArvutamineUI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PlaatideArvutamineUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnArvuta;
    private javax.swing.JCheckBox chkLoigatudPlaadid;
    private javax.swing.JCheckBox chkTervedPlaadid;
    private javax.swing.JCheckBox chkVuugivahe;
    private javax.swing.JComboBox<String> cmbPlaatLaius;
    private javax.swing.JComboBox<String> cmbPlaatPikkus;
    private javax.swing.JComboBox<String> cmbPorandLaius;
    private javax.swing.JComboBox<String> cmbPorandPikkus;
    private javax.swing.JComboBox<String> cmbVuugivahePikkus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner spnPlaatLaius;
    private javax.swing.JSpinner spnPlaatPikkus;
    private javax.swing.JSpinner spnPorandLaius;
    private javax.swing.JSpinner spnPorandPikkus;
    private javax.swing.JSpinner spnVuugivahePikkus;
    private javax.swing.JTextArea txtaData;
    // End of variables declaration//GEN-END:variables
}
